
#pragma config(Sensor, S1,     touhSensor,     sensorTouch)
#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//const tSensors touchSensor = (tSensors) S1;
const tSensors lightSensor = (tSensors) S2;

//prototypes
void avoidCells(void);
int NavigateGrid[5][5];
int thresholdValue;
int Colour(int threshold);

task main()
{
    int i, j;
	//initialising the grid
	for (i = 0; i < 5; i++)
	{
		for (j = 0; i < 5; i ++)
		{
			NavigateGrid[i][j] = 0;
		}//end for
	}//end for
	NavigateGrid[0][2] = 99;
	//getting threshold
	int light=50;
	int dark=20;
	int sum = light + dark;
	thresholdValue = sum/2;

	while(1==1)//while always true
	{
        //while the lightSensor senses white(greater than 40)
		while(SensorValue(lightSensor) > 40)
		{
            //move forward at a speed of 35 for 0.2 seconds
			motor[motorB] = 35;
			motor[motorC] = 35;
			wait1Msec(200);

			//call function avoidlines
			avoidCells();

		}//end outer while

	}//end while true
}//end main()

int Colour(int threshold)
{
    //detecting light and dark values
	if (SensorValue(lightSensor) < threshold)
        //detecting black cell
	{
		nxtDisplayCenteredTextLine(4, "Black Cell");
		wait1Msec(1000);
		return 1;
	}//end if
	else
	{
        //detecting white cell
		nxtDisplayCenteredTextLine(4, "White Cell");
		wait1Msec(1000);
		return 0;
	}//end else
}//end function

void avoidlines(void)
{
    //while the light sensor senses a black 
	while(SensorValue(lightSensor) < 40)
		{
                //detects the black cell
				nMotorEncoder[motorB] = 0;//reset the value of encoder B to zero
				nMotorEncoder[motorC] = 0;//reset the value of encoder C to zero
				nMotorEncoderTarget[motorB] = 60;//set taret value of 60 to motorB
				nMotorEncoderTarget[motorC] = 60;//set taret value of 60 to motorC
				motor[motorB] = 50;//turn on motorB at 50% power
				motor[motorC] = 50;//turn on motorC at 50% power
				wait1Msec(280);

            if(SensorValue(lightSensor) < 40)
				{
                    //reverses and turns the robot when black cell detected at a speed of 55
					motor[motorB] = -55;
					motor[motorC] = -55;
					wait1Msec(220);

					motor[motorB] = -55;
					motor[motorC] = 55;
					wait1Msec(300);
				}//end if
		}//end while
}//end avoidlines